FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source
COPY . .
RUN dotnet restore "./MerlinBot_Service/MerlinBot_service.csproj" --disable-parallel
RUN dotnet publish "./MerlinBot_Service/MerlinBot_service.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "MerlinBot_Service.dll"]